#ifndef MAINWINDOW_H
#define MAINWINDOW_H
#include <QMainWindow>
#include <gui\gamewindow.h>
#include "logic\cgame.h"
#include "logic\cmap.h"
#include<gui\cgtank.h>

QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; }
QT_END_NAMESPACE

class MainWindow : public QMainWindow //! GUI menu class
{
    Q_OBJECT

public:
    MainWindow(QWidget *parent = nullptr);
    ~MainWindow();
    void display_tanks(CGTank *tank,QTableWidget *table,QGraphicsView *t_view);
private slots:
    //! GUI Interactive Method. generated by Forms
    void on_Play_clicked();
    //! GUI Interactive Method. generated by Forms
    void on_Settings_clicked();
    //! GUI Interactive Method. generated by Forms
    void on_Quit_clicked();
    //! GUI Interactive Method. generated by Forms
    void on_start_game_clicked();
    //! GUI Interactive Method. generated by Forms
    void on_back_op_clicked();
    //! GUI Interactive Method. generated by Forms
    void on_back_play_clicked();
    //! GUI Interactive Method. generated by Forms
    void on_Reset_clicked();
    //! GUI Interactive Method. generated by Forms
    void on_Light_tank_toggled(bool checked);
    //! GUI Interactive Method. generated by Forms
    void on_Medium_tank_toggled(bool checked);
    //! GUI Interactive Method. generated by Forms
    void on_Heavy_tank_toggled(bool checked);

private:
    //! Tank which is chosen by player
    int tank_choice=0;
    GameWindow *gamewindow=nullptr;
    Ui::MainWindow *ui;
};
#endif // MAINWINDOW_H
